server:
 port: 9000

spring:
 datasource:
  url: jdbc:mysql://konnnectdb.chvrddq1gept.eu-west-2.rds.amazonaws.com/KonnnectDB
  username: sdb_admin
  password: C4lyp50007
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL55Dialect
    format_sql: true